serial_no: "244222076237"
rgb_camera.color_profile: 640x480x15
depth_module.depth_profile: 640x480x15
depth_module.infra_profile: 640x480x15
pointcloud.enable: True
pointcloud.stream_filter: 0
pointcloud.stream_index_filter: -1